<?php

namespace AMiE\OffreEmploiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotClefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotClefRepository extends EntityRepository
{
}
