<?php

namespace AMiE\OffreEmploiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OffreEmploi_MotClefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreEmploi_MotClefRepository extends EntityRepository
{
}
