<?php
namespace AMiE\OffreEmploiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AMiE\UserBundle\Entity\User;

/**
 * OffreEmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreEmploiRepository extends EntityRepository
{
    public function searchOffre(User $entreprise)
    {
        $id = $entreprise->getId();
        $query = 'SELECT o FROM AMiE\OffreEmploiBundle\Entity\OffreEmploi o WHERE o.idEntreprise = :id';
        $request = $this->getEntityManager()->createQuery($query);

        $request->setParameters(array('id' => $id));

        return $request;
    }

    public function searchNbOffre($entreprise)
    {
        $query = 'SELECT count(o) FROM AMiE\OffreEmploiBundle\Entity\OffreEmploi o WHERE o.nomEntreprise = :entreprise';
        $request = $this->getEntityManager()->createQuery($query);

        $request->setParameters(array('entreprise' => $entreprise));

        return $request;
    }
}
